"""Enumerations for the FinQuest adaptive learning engine.

This module has no knowledge of any infrastructure (databases, queues,
HTTP frameworks, ML/LLM/RAG libraries, orchestration engines, etc.).
"""

from enum import StrEnum


class LearningSessionStatus(StrEnum):
    STARTED = "STARTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"
    EXPIRED = "EXPIRED"


class LearningSessionType(StrEnum):
    DAILY_PRACTICE = "DAILY_PRACTICE"
    DIAGNOSTIC = "DIAGNOSTIC"
    REVIEW = "REVIEW"
    LESSON_PRACTICE = "LESSON_PRACTICE"
    FREE_PRACTICE = "FREE_PRACTICE"


class DiagnosticAssessmentStatus(StrEnum):
    CREATED = "CREATED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class RecommendationType(StrEnum):
    NEW_LESSON = "NEW_LESSON"
    PRACTICE_EXERCISE = "PRACTICE_EXERCISE"
    REVIEW_EXERCISE = "REVIEW_EXERCISE"
    MISCONCEPTION_REMEDIATION = "MISCONCEPTION_REMEDIATION"
    PREREQUISITE_REVIEW = "PREREQUISITE_REVIEW"
    DIAGNOSTIC_EXERCISE = "DIAGNOSTIC_EXERCISE"
    SESSION_COMPLETE = "SESSION_COMPLETE"
    NO_ELIGIBLE_CONTENT = "NO_ELIGIBLE_CONTENT"


class RecommendationReason(StrEnum):
    ACTIVE_MISCONCEPTION = "ACTIVE_MISCONCEPTION"
    OVERDUE_REVIEW = "OVERDUE_REVIEW"
    LOW_MASTERY = "LOW_MASTERY"
    PREREQUISITE_GAP = "PREREQUISITE_GAP"
    INCOMPLETE_LESSON = "INCOMPLETE_LESSON"
    RECENT_FAILURE = "RECENT_FAILURE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    DIAGNOSTIC_COVERAGE = "DIAGNOSTIC_COVERAGE"
    NEW_CONTENT = "NEW_CONTENT"
    DAILY_GOAL_REACHED = "DAILY_GOAL_REACHED"
    NO_ELIGIBLE_EXERCISE = "NO_ELIGIBLE_EXERCISE"


class ReviewScheduleStatus(StrEnum):
    NOT_SCHEDULED = "NOT_SCHEDULED"
    SCHEDULED = "SCHEDULED"
    DUE = "DUE"
    OVERDUE = "OVERDUE"
    COMPLETED = "COMPLETED"
    SUSPENDED = "SUSPENDED"


class AdaptiveDecisionStatus(StrEnum):
    GENERATED = "GENERATED"
    ACCEPTED = "ACCEPTED"
    SKIPPED = "SKIPPED"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"


class DifficultyAdjustment(StrEnum):
    DECREASE = "DECREASE"
    KEEP = "KEEP"
    INCREASE = "INCREASE"


class DiagnosticSkillResult(StrEnum):
    NOT_ASSESSED = "NOT_ASSESSED"
    NEEDS_FOUNDATION = "NEEDS_FOUNDATION"
    DEVELOPING = "DEVELOPING"
    READY = "READY"
    STRONG = "STRONG"
