"""Enumerations for the FinQuest virtual-portfolio and decision-journal engine.

This module has no knowledge of any infrastructure (databases, queues,
HTTP frameworks, pandas/NumPy/SciPy, yfinance, ML/LLM/RAG libraries,
orchestration engines, etc.).
"""

from enum import StrEnum


class VirtualPortfolioStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class PortfolioTransactionType(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class PortfolioTransactionStatus(StrEnum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PortfolioDecisionAction(StrEnum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    REBALANCE = "REBALANCE"
    RESEARCH_MORE = "RESEARCH_MORE"


class PortfolioValuationRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    NO_PRICE_DATA = "NO_PRICE_DATA"


class PortfolioRiskLevel(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    UNKNOWN = "UNKNOWN"


class PortfolioFeedbackCode(StrEnum):
    POSITION_CONCENTRATION = "POSITION_CONCENTRATION"
    SECTOR_CONCENTRATION = "SECTOR_CONCENTRATION"
    LIMITED_DIVERSIFICATION = "LIMITED_DIVERSIFICATION"
    HIGH_CASH_ALLOCATION = "HIGH_CASH_ALLOCATION"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LARGE_DRAWDOWN = "LARGE_DRAWDOWN"
    HIGH_TURNOVER = "HIGH_TURNOVER"
    BENCHMARK_NOT_CONFIGURED = "BENCHMARK_NOT_CONFIGURED"
    MISSING_PRICE_DATA = "MISSING_PRICE_DATA"
    BROAD_DIVERSIFICATION = "BROAD_DIVERSIFICATION"
    LOW_TURNOVER = "LOW_TURNOVER"
    RISK_NOT_DOCUMENTED = "RISK_NOT_DOCUMENTED"
    HORIZON_NOT_DOCUMENTED = "HORIZON_NOT_DOCUMENTED"
    OVERCONFIDENT_DECISION = "OVERCONFIDENT_DECISION"
    DECISION_RATIONALE_DOCUMENTED = "DECISION_RATIONALE_DOCUMENTED"


class TradeRejectionReason(StrEnum):
    PORTFOLIO_NOT_ACTIVE = "PORTFOLIO_NOT_ACTIVE"
    SECURITY_NOT_FOUND = "SECURITY_NOT_FOUND"
    SECURITY_NOT_ACTIVE = "SECURITY_NOT_ACTIVE"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    NO_EXECUTION_PRICE = "NO_EXECUTION_PRICE"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    INSUFFICIENT_QUANTITY = "INSUFFICIENT_QUANTITY"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    FRACTIONAL_SHARES_DISABLED = "FRACTIONAL_SHARES_DISABLED"
    DUPLICATE_IDEMPOTENCY_KEY = "DUPLICATE_IDEMPOTENCY_KEY"
    SIMULATION_DATE_REGRESSION = "SIMULATION_DATE_REGRESSION"


class DecisionConfidence(StrEnum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
