"""Enumerations shared by all domain models and service contracts."""

from enum import StrEnum


class Exchange(StrEnum):
    NASDAQ = "NASDAQ"
    NYSE = "NYSE"
    AMEX = "AMEX"
    OTHER = "OTHER"


class DocumentType(StrEnum):
    NEWS = "NEWS"
    COMPANY_RELEASE = "COMPANY_RELEASE"
    REGULATORY_FILING = "REGULATORY_FILING"
    EARNINGS_TRANSCRIPT = "EARNINGS_TRANSCRIPT"
    ANALYST_REPORT = "ANALYST_REPORT"
    OTHER = "OTHER"


class EventType(StrEnum):
    EARNINGS = "EARNINGS"
    GUIDANCE = "GUIDANCE"
    PRODUCT = "PRODUCT"
    CONTRACT = "CONTRACT"
    CUSTOMER = "CUSTOMER"
    REGULATION = "REGULATION"
    LEGAL = "LEGAL"
    MANAGEMENT = "MANAGEMENT"
    FINANCING = "FINANCING"
    MERGER_ACQUISITION = "MERGER_ACQUISITION"
    ANALYST_ACTION = "ANALYST_ACTION"
    MACRO = "MACRO"
    SECTOR = "SECTOR"
    OTHER = "OTHER"


class Direction(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class CriticalPointType(StrEnum):
    LOCAL_MINIMUM = "LOCAL_MINIMUM"
    LOCAL_MAXIMUM = "LOCAL_MAXIMUM"
    BREAKOUT = "BREAKOUT"
    BREAKDOWN = "BREAKDOWN"
    GAP_UP = "GAP_UP"
    GAP_DOWN = "GAP_DOWN"
    VOLUME_SPIKE = "VOLUME_SPIKE"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    SUPPORT_TEST = "SUPPORT_TEST"
    RESISTANCE_TEST = "RESISTANCE_TEST"
    TREND_REVERSAL = "TREND_REVERSAL"


class PredictionLabel(StrEnum):
    OUTPERFORM = "OUTPERFORM"
    NEUTRAL = "NEUTRAL"
    UNDERPERFORM = "UNDERPERFORM"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class AlertSeverity(StrEnum):
    INFO = "INFO"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnalysisStatus(StrEnum):
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
